### ISSUE TITLE
Bug with Low-light vision

### ISSUE THREAD

**Issue by V4leR05** [schultzcole/FVTT-No-Summon-Vision#1]
Found a bug regarding low-light vision, it seems that if a token (for example a torch) is emitting light, an actor with low-light vision doesn't get the "improved" vision. On the other hand, this is not true for environmental lights, where low-light vision works as intended. 

I'm sure that the problem comes from this module since activating-deactivating it creates/solves. 
Find attached the screenshots I made.
Cheers

Foundry version: 0.6.5
Game System: Pathfinder1e 0.67
No Summon Vision version: 1.0.0

![1](https://user-images.githubusercontent.com/20427514/88384245-5ad1f680-cdac-11ea-9422-2dc9b94a656b.png)
![2](https://user-images.githubusercontent.com/20427514/88384248-5b6a8d00-cdac-11ea-8e6c-ade8724a17f8.PNG)
![3](https://user-images.githubusercontent.com/20427514/88384251-5b6a8d00-cdac-11ea-89bc-a44120fe22fc.png)
![4](https://user-images.githubusercontent.com/20427514/88384252-5b6a8d00-cdac-11ea-9d1a-f0971576f76e.png)
![5](https://user-images.githubusercontent.com/20427514/88384253-5c032380-cdac-11ea-97c9-63a27357e0c0.png)

**Comment by schultzcole** [comment]
Closing because this module's functionality has been absorbed into core in 0.7 and thus this module will no longer be supported.
